Repository Yamato-Security/hayabusa, pull requests merged in 2022-02, with the labels that each got.

#378 Hotfix/no output colorcode in no true color#376
  README-English.md
  README-Japanese.md
  src/afterfact.rs
  src/detections/configs.rs
Labels: bug

#398 added live analysys feature
  Cargo.lock
  Cargo.toml
  README-English.md
  README-Japanese.md
  src/detections/configs.rs
  src/main.rs
Labels: enhancement

#397 added mitre attack data output in csv output
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/print.rs
Labels: enhancement

#399 Fixed Readme
  README-English.md
  README-Japanese.md
  README.md
Labels: documentation

#396 fixed detection lack when tab and enter control character in event record#395
  config/regex/record_data_filter.txt
  src/detections/print.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/filter.rs
Labels: bug

#400 Add: Table of Contents to README
  README-Japanese.md
  README.md
Labels: documentation

#401 Added update command#391 submodule ver
  .gitmodules
  README-Japanese.md
  README.md
  src/main.rs
Labels: enhancement

#408 Bug/ Fixed error when target environment is not installed vcc redistribute package
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: bug

#415 Document/describe wildcard is case insensitive#411
  doc/AboutRuleCreation-English.md
  doc/AboutRuleCreation-Japanese.md
Labels: documentation

#392 added update command #391
  .gitmodules
  Cargo.lock
  Cargo.toml
  README-Japanese.md
  README.md
  src/detections/configs.rs
  src/main.rs
Labels: enhancement

#423 Update issue templates #419
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#424 Hotfix/not update submodule update#422
  src/main.rs
Labels: bug

#427 readme update-RuleDocToHayabusRulesRepo BugSub
  README-Japanese.md
  README.md
  doc/AboutRuleCreation-English.md
  doc/AboutRuleCreation-Japanese.md
  doc/CountRulePattern-1-EN.png
  doc/CountRulePattern-1-JP.png
  doc/CountRulePattern-2-EN.png
  doc/CountRulePattern-2-JP.png
  doc/CountRulePattern-3-EN.png
  doc/CountRulePattern-3-JP.png
  doc/CountRulePattern-4-EN.png
  doc/CountRulePattern-4-JP.png
Labels: documentation

#433 Hotfix/failed twice update rule#432
  src/main.rs
Labels: bug
