Repository Yamato-Security/hayabusa, pull requests merged in 2022-04, with the labels that each got.

#485 Fixed output stop when control char exist in windows terminal
  README-Japanese.md
  README.md
  src/afterfact.rs
Labels: bug

#483 reduce output mitre attack detail tachnique No. by config file
  Cargo.lock
  Cargo.toml
  config/output_tag.txt
  src/detections/detection.rs
  src/detections/print.rs
  test_files/config/output_tag.txt
Labels: enhancement

#482 Enhance/warning architecture#478
  src/main.rs
Labels: bug, enhancement

#459 Feature/level tuning#390
  Cargo.lock
  README-Japanese.md
  README.md
  config/level_tuning.txt
  src/detections/configs.rs
  src/filter.rs
  src/lib.rs
  src/main.rs
  src/options/level_tuning.rs
  src/options/mod.rs
  test_files/config/level_tuning.txt
  test_files/config/level_tuning_error1.txt
  test_files/config/level_tuning_error2.txt
Labels: enhancement

#486 twitter link fix
  README-Japanese.md
  README.md
Labels: documentation

#488 reduce output mitre attck agg cond details tactic no to aggregation condition
  src/detections/detection.rs
Labels: enhancement

#473 v1.2 changelog update
  CHANGELOG-Japanese.md
  CHANGELOG.md
Labels: documentation

#508 Added Channel column and Channel Abbreviations
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  config/channel_abbreviations.txt
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/print.rs
  src/detections/utils.rs
Labels: enhancement

#512 level_tuning.txtのパスを./rules/configに移動
  README-Japanese.md
  README.md
  config/level_tuning.txt
  src/detections/configs.rs
  src/filter.rs
  src/main.rs
  src/options/level_tuning.rs
  src/yaml.rs
Labels: bug

#509 changed force update to hayabusa-rules #490
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README-Japanese.md
  README.md
  src/main.rs
Labels: enhancement

#516 Fixed update bug when rules repository not exist and rules folder exist
  src/main.rs
Labels: bug
