Repository Yamato-Security/hayabusa, pull requests merged in 2022-12, with the labels that each got.

#834 fixed pivot-keywords-list short option
  README-Japanese.md
  README.md
Labels: documentation

#836 Endswithfieldの対応
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/filter.rs
Labels: enhancement

#837 Reduced memory usage of `DetectInfo`/`EvtxRecordInfo`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/utils.rs
Labels: enhancement

#841 hide debug option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: enhancement

#846 fix: bug when no command and global options
  src/main.rs
Labels: bug

#856 Generate coverage data in CI
  .github/workflows/coverage.yml
  README-Japanese.md
  README.md
Labels: enhancement

#853 Removed unnecessary newline when jsonl option is enable(v1.9.0)
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug

#854 Removed unnecessary newline when jsonl option is enable(v2)
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug
