Repository Yamato-Security/hayabusa, pull requests merged in 2022-07, with the labels that each got.

#619 Fixed error error occurs when executing cargo run because the files in the config folder cannot be read.
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/print.rs
  src/detections/utils.rs
  src/main.rs
Labels: bug

#622 Feature/improve parallel processing
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/mod.rs
  src/detections/print.rs
  src/detections/rule/count.rs
  src/detections/rule/mod.rs
  src/filter.rs
  src/main.rs
  src/options/update_rules.rs
  src/timeline/statistics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#625 Display relative rules path
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  README-Japanese.md
  README.md
  src/afterfact.rs
  src/detections/detection.rs
Labels: bug, enhancement

#636 Bugfix error when target env not installed vc redistribute package
  Cargo.toml
  build.rs
  src/main.rs
Labels: bug
