Repository Yamato-Security/hayabusa, pull requests merged in 2022-03, with the labels that each got.

#435 Readme update 32bit cross compile add
  README-Japanese.md
  README.md
Labels: documentation

#434 Fix/fix clippy warn
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/print.rs
  src/detections/rule/aggregation_parser.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/filter.rs
  src/main.rs
  src/notify/slack.rs
  src/timeline/mod.rs
  src/timeline/statistics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: Priority:Medium

#448 readme update screenshots etc
  README-Japanese.md
  README.md
  screenshots/Hayabusa-Results.png
  screenshots/HayabusaResultsSummary.png
Labels: documentation

#442 aliasキーがない場合もEvent.EventDataを自動で走査する
  src/detections/print.rs
  src/detections/utils.rs
  src/filter.rs
Labels: enhancement

#450 changed downcast library from mopa to downcast_rs #447
  Cargo.lock
  Cargo.toml
  src/detections/rule/matchers.rs
  src/detections/rule/selectionnodes.rs
  src/main.rs
Labels: enhancement

#454 Document/add badges#453
  README-Japanese.md
  README.md
Labels: documentation

#455 readmeの更新
  README-Japanese.md
  README.md
  screenshots/Hayabusa-Startup.png
  screenshots/MacOS-RunError-1-EN.png
  screenshots/MacOS-RunError-1-JP.png
  screenshots/MacOS-RunError-2-EN.png
  screenshots/MacOS-RunError-2-JP.png
  screenshots/MacOS-RunError-3-EN.png
  screenshots/MacOS-RunError-3-JP.png
Labels: documentation

#464 Feature/#440 refactoring #395
  src/detections/print.rs
  src/detections/rule/matchers.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/filter.rs
Labels: enhancement

#468 fix degrade for pull req #464
  src/detections/print.rs
  src/detections/utils.rs
Labels: bug

#471 Enhancement: add config config #456
  README-Japanese.md
  README.md
  src/detections/configs.rs
  src/filter.rs
Labels: enhancement

#476 [Bugfix] exculde load yml in git folder#472
  src/yaml.rs
Labels: bug
