Repository Yamato-Security/hayabusa, pull requests merged in 2022-09, with the labels that each got.

#684 Fixed total events is actually the number of scanned events
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: bug

#682 Fixed custom config directory doesnt load files
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/message.rs
  src/detections/utils.rs
  src/main.rs
  src/options/profile.rs
Labels: bug

#686 Changed channel field in channel abbreviationstxt case insensitive
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
Labels: enhancement

#691 Added color to saved alerts and events total events analyzed
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: enhancement

#696 Added code blue 2022 blue-box badge
  README-Japanese.md
  README.md
Labels: documentation

#670 Added Output to json
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  README-Japanese.md
  README.md
  src/afterfact.rs
  src/detections/configs.rs
Labels: enhancement

#698 Added option of output to jsonl
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/afterfact.rs
  src/detections/configs.rs
Labels: enhancement

#700 update screenshot
  .gitignore
  README-1.6.0-Japanese.pdf
  README-1.6.0.pdf
  screenshots/Hayabusa-Results.png
Labels: documentation

#711 Added display new version of hayabusa when updating
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/options/mod.rs
  src/options/update.rs
Labels: enhancement

#715 Added logo,png in html report and Refactoring
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/utils.rs
  src/filter.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/update.rs
Labels: enhancement

#717 fix broken link
  README-Japanese.md
  README.md
Labels: documentation

#718 changed html report static resource path to ./config/html_report
  config/html_report/hayabusa_report.css
  config/html_report/logo.png
  src/options/htmlreport.rs
Labels: enhancement

#719 hayabusa_report.css implementation
  config/html_report/background_image.jpg
  config/html_report/hayabusa_report.css
Labels: enhancement

#720 Unified table of analyze metrics and logon summary of event ids when scanning directory together
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/main.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: enhancement
