Repository Yamato-Security/hayabusa, pull requests merged in 2022-06, with the labels that each got.

#555 display default channel name if not defined
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  config/channel_abbreviations.txt
  src/detections/detection.rs
  src/detections/print.rs
Labels: enhancement

#562 fixed bug hayabusa crashes when level is not valid
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug

#559 separate excluded and noisy rules count
  CHANGELOG-Japanese.md
  CHANGELOG.md
  screenshots/Hayabusa-Startup.png
  src/detections/detection.rs
  src/filter.rs
  src/yaml.rs
Labels: enhancement

#569 strip symbols when compiling
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/pivot.rs
  src/detections/print.rs
  src/detections/rule/matchers.rs
  src/detections/utils.rs
  src/main.rs
  src/timeline/timelines.rs
Labels: enhancement

#571 replaced unnecessary clone use
  Cargo.lock
  Cargo.toml
  src/detections/pivot.rs
  src/detections/print.rs
  src/main.rs
  src/notify/mod.rs
  src/notify/slack.rs
Labels: enhancement

#578 specified field data from multi data in details and output column bug fix
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  README-Japanese.md
  src/afterfact.rs
  src/detections/print.rs
Labels: bug, enhancement

#584 Display record id by default
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  screenshots/Hayabusa-Results.png
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/print.rs
Labels: enhancement

#585 output processing rules msg and rule status metrics
  CHANGELOG-Japanese.md
  CHANGELOG.md
  screenshots/Hayabusa-Startup.png
  src/detections/detection.rs
  src/detections/utils.rs
  src/main.rs
  src/yaml.rs
Labels: enhancement

#593 output default details when undefined details
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/detections/detection.rs
  src/detections/print.rs
  test_files/config/default_details.txt
Labels: enhancement

#598 new feature exclude status
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/detections/configs.rs
  src/detections/detection.rs
  src/filter.rs
  src/yaml.rs
Labels: enhancement

#601 hayabusa config folder is adjusted base on execution path
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/print.rs
  src/detections/rule/matchers.rs
  src/detections/utils.rs
  src/main.rs
Labels: enhancement

#610 Print all field info when no details are defined
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/detections/detection.rs
  src/detections/utils.rs
Labels: enhancement

#614 updated document #355
  README-Japanese.md
  README.md
  config/profiles.txt
Labels: documentation
