Repository Yamato-Security/hayabusa, pull requests merged in 2022-10, with the labels that each got.

#733 Fixed duplicate event outputted with metric option due to sum up of event IDs key name.
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/metrics.rs
Labels: bug

#734 Added output rule authors in standard out
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/main.rs
Labels: enhancement

#736 Excluded null channel in record from detection and metric.
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#752 Limited rule author names to 40 characters
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: enhancement

#754 move saved file line
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/options/update.rs
Labels: enhancement

#755 Fixed fields get moved over in JSON/JSONL output when driveletter in the field
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug

#763 add companion projects to readme
  README-Japanese.md
  README.md
Labels: documentation

#765 Add unique and total detections to html report
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config/html_report/hayabusa_report.css
  src/afterfact.rs
  src/detections/detection.rs
  src/main.rs
  src/options/htmlreport.rs
Labels: enhancement

#769 fix: improve error msg when update-rules failed with Admin privileges
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
  src/options/update.rs
Labels: enhancement

#772 Added profile alias about rule to output profile and improved github template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  config/profiles.yaml
  src/detections/detection.rs
  src/options/profile.rs
Labels: enhancement

#776 Added output allfieldinfo field in jsonl in array of separate fields
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  config/profiles.yaml
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/options/profile.rs
  test_files/config/default_profile.yaml
  test_files/config/profiles.yaml
Labels: enhancement

#777 chg: build.rs(for vc runtime) to rustflags in config.toml and replace default global memory allocator with mimalloc.
  .cargo/config.toml
  .cargo/msvcrt.lib
  .github/workflows/rust.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  build.rs
  src/main.rs
Labels: enhancement

#779 refactor: Remove unnecessary msvcrt.lib
  .cargo/config.toml
  .cargo/msvcrt.lib
Labels: enhancement

#781 fix: readme linux chmod command example
  README-Japanese.md
  README.md
Labels: documentation

#783 Fixed rule author count bug
  .github/pull_request_template.md
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug
