Repository Yamato-Security/hayabusa, pull requests merged in 2023-10, with the labels that each got.

#1190 fixed removed `AllFieldInfo` and `ExtraFieldInfo` field newline and tab char
  src/afterfact.rs
  src/detections/message.rs
  src/detections/utils.rs
Labels: bug

#1187 fixed duplicate fields are outputted in extrafieldinfo
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/utils.rs
  src/options/level_tuning.rs
Labels: bug

#1196 Add `--include-tag` and `--exclude-tag` options in `pivot-keywords-list` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/main.rs
Labels: enhancement

#1198 UI(art, main): added new art Jack-o'-Lantern #1194
  art/halloween.txt
  src/main.rs
Labels: enhancement

#1200 fix: Update GitHub Actions for Integration test
  .github/workflows/integration-test.yml
Labels: enhancement

#1199 fixed spaces are deleted in some field data in standard output
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: invalid

#1203 update readme
  README-Japanese.md
  README.md
Labels: documentation

#1205 add explanation about rule sets
  README-Japanese.md
  README.md
Labels: documentation
