Repository Yamato-Security/hayabusa, pull requests merged in 2023-02, with the labels that each got.

#902 Updated krapslog
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
Labels: enhancement

#903 added --exact-level option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/level_tuning.rs
  src/options/profile.rs
  src/options/update.rs
  src/yaml.rs
Labels: enhancement

#907 Fixed unwrap error when geoip field was not found in ext_field
  src/afterfact.rs
Labels: bug

#908 Reordered based on long option
  .codecov.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#909 update changelog
  CHANGELOG-Japanese.md
  CHANGELOG.md
Labels: documentation

#915 Fixed panic of getting file size metadata
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: bug

#919 added MaxMind link to license section
  README-Japanese.md
  README.md
Labels: documentation

#921 Reduce memory usage when reading `JSONL` file
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/utils.rs
  src/main.rs
Labels: enhancement

#926 Added support for `|base64offset|contains` pipe keyword
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#929 fixed logon summary and metrics do not show the first and last timestamp with json input
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: bug

#934 933 bug event titles are not shown in metrics command anymore
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: bug

#937 print first and last timestamp in metrics command when the target is a directory
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/timelines.rs
Labels: enhancement

#936 Added abbreviation feature to provider names
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/detections/detection.rs
  src/timeline/timelines.rs
Labels: enhancement

#939 add first and last timestamp to results summary
  CHANGELOG-Japanese.md
  CHANGELOG.md
  config/html_report/hayabusa_report.css
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/utils.rs
  src/main.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: enhancement
