Repository Yamato-Security/hayabusa, pull requests merged in 2023-01, with the labels that each got.

#876 fix readme typo
  README-Japanese.md
Labels: documentation

#878 Add jq documentation
  README-Japanese.md
  README.md
  doc/AnalysisWithJQ-English.md
  doc/AnalysisWithJQ-Japanese.md
Labels: documentation

#882 Improving speed by changing `EventID` matching process from `regular expression` to `exact string matching`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  doc/AnalysisWithJQ-English.md
  doc/AnalysisWithJQ-Japanese.md
  src/detections/rule/selectionnodes.rs
Labels: enhancement

#883 Improving speed by adding `string length match` before `regular expression match`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/detections/configs.rs
  src/detections/rule/matchers.rs
Labels: enhancement

#884 Improving speed by using `eq_ignore_ascii_case()` before `regular expression match`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#889 #888 fix mitm CVE 2023 22742 vulnerability
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
Labels: vulnerability

#890 Imporving speed by changing `wildcard` search process from `regular expression` match to `starts_with/ends_with` match
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#894 Reduce memory usage by removing unnecessary regex
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/detections/rule/matchers.rs
Labels: enhancement

#898 Reduce memory usage by changing wildcard pattern regex to `contains` match
  .codecov.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/afterfact.rs
  src/debug/checkpoint_process_timer.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/rule/aggregation_parser.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/utils.rs
  src/filter.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/level_tuning.rs
  src/options/profile.rs
  src/options/update.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: bug, enhancement
