Repository Yamato-Security/hayabusa, pull requests merged in 2023-03, with the labels that each got.

#947 Improve speed by str contains method
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/utils.rs
  src/yaml.rs
Labels: enhancement

#948 Added support contains all field
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
Labels: enhancement

#950 add enable-unsupported-rules option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
  test_files/rules/unsupported/1.yml
Labels: enhancement

#953 add dfir timeline diagram
  README-Japanese.md
  README.md
  doc/DFIR-TimelineCreation-EN.png
  doc/DFIR-TimelineCreation-JP.png
Labels: documentation

#954 Fix: set-default-profile's README option was incorrect
  README-Japanese.md
  README.md
  src/afterfact.rs
  src/detections/pivot.rs
  src/detections/utils.rs
Labels: documentation

#957 feat: Support `1 of selection*` and `all of selection*`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/detections/rule/condition_parser.rs
Labels: enhancement

#958 Doc hayabusa developer performance guide
  README-Japanese.md
  README.md
  doc/01_mi_stats_print_out.png
  doc/02-heaptrack.png
  doc/03-heaptrack.png
  doc/RustPerformance-English.md
  doc/RustPerformance-Japanese.md
Labels: documentation

#961 feat: Support `cidr` rule
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/detections/rule/matchers.rs
Labels: enhancement

#966 Fixed bug update rules command panics on 2.3.0
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: bug

#967 Added double quote in csv fields
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/afterfact.rs
Labels: enhancement

#968 add short options
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: enhancement

#970 sorted filtering options
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: enhancement

#975 Add Powershell scriptblock extraction to jq docs
  doc/AnalysisWithJQ-English.md
  doc/AnalysisWithJQ-Japanese.md
Labels: documentation

#978 fixed level tuning command panics on ver 2.3.1 2.3.2
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/yaml.rs
Labels: bug

#981 Trim extra space in levels when outputting to files
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: enhancement
