Repository Yamato-Security/hayabusa, pull requests merged in 2023-05, with the labels that each got.

#1027 fix: add another backslash before the asterisk when rule ends with a backslash
  .gitignore
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/detections/rule/matchers.rs
Labels: bug

#1030 details check hayabusa version when update-rules option is used
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#1032 Fixed bug info alert shows up twice in results summary
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug

#1034 Sort search timeline order
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/search.rs
  src/timeline/timelines.rs
Labels: enhancement

#1023 Deleted return characters in output of csv timeline command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: enhancement

#1044 enable --no-color with pivot of headers
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
  src/options/pivot.rs
Labels: enhancement

#1043 Fixed Data in AccessMask field are not separated by spaces in the details field
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
Labels: invalid

#1047 perf: Reduced memory usage by removing unnecessary regex compilation
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#1052 added ExtraFieldInfo profile field
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config/default_profile.yaml
  config/profiles.yaml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/options/profile.rs
Labels: enhancement

#1053 Add argument conflict checks
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: enhancement

#1062 fixed MitreTactics, MitreTags, OtherTags do not output in json timeline output
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/message.rs
  src/main.rs
Labels: bug

#1064 added output which output profile is used
  CHANGELOG-Japanese.md
  CHANGELOG.md
  config/default_profile_name.txt
  config/html_report/hayabusa_report.css
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
Labels: enhancement
