Repository Yamato-Security/hayabusa, pull requests merged in 2023-09, with the labels that each got.

#1176 optimize max detect records
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#1178 crate update
  Cargo.lock
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
Labels: enhancement

#1173 Refactorer JSON output processing
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/field_data_map.rs
  src/detections/message.rs
  src/detections/utils.rs
  src/timeline/search.rs
Labels: enhancement

#1146 Fixed json fields get moved over
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/field_data_map.rs
  src/detections/message.rs
  src/detections/utils.rs
  src/timeline/search.rs
Labels: bug

#1185 update readme
  README-Japanese.md
Labels: documentation
