Repository Yamato-Security/hayabusa, pull requests merged in 2023-06, with the labels that each got.

#1070 docs(README): added SANS DFIR Summit badge Add SANS DFIR Summit 2023 badge
  README-Japanese.md
  README.md
Labels: documentation

#1073 added rule author name in html report
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: enhancement

#1074 Fixed no detection frequency timeline output when no-summary option is used.
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
Labels: invalid

#1079 fixed non transportable html output
  CHANGELOG-Japanese.md
  CHANGELOG.md
  config/html_report/hayabusa_report.css
  src/options/htmlreport.rs
  test_files/config/favicon.png
Labels: enhancement

#1076 Added overwrite existing output files option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
  src/yaml.rs
  test_files/evtx/test_metrics.json
  test_files/rules/yaml/test_json_detect.yml
Labels: enhancement

#1080 modified the tables fit on a 120 character terminal
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/main.rs
Labels: enhancement

#1084 📚 Add Timesketch instructions for v2
  doc/TimesketchImport/TimesketchImport-English.md
  doc/TimesketchImport/TimesketchImport-Japanese.md
Labels: documentation

#1082 fixed unescaped control character c causing jq parsing errors
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
Labels: invalid

#1093 added output search results to json
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/timeline/search.rs
  src/timeline/timelines.rs
Labels: enhancement

#1094 Feature/1067 word wrap in cell when event title is long
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/timelines.rs
Labels: enhancement

#1101 fix: README modify metrics command example
  README-Japanese.md
  README.md
Labels: documentation

#1102 fix: Ignore corrupt timestamp record when calculating the `First Timestamp`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/metrics.rs
Labels: bug

#1106 fixed `metrics` and `logon-summary` records and `csv-timline` show different total event records
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
  src/timeline/timelines.rs
Labels: bug

#1109 added filter on tags
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
  test_files/rules/level_yaml/critical.yml
  test_files/rules/level_yaml/high.yml
  test_files/rules/level_yaml/info.yml
  test_files/rules/level_yaml/low.yml
  test_files/rules/level_yaml/medium.yml
Labels: enhancement
