Repository Yamato-Security/hayabusa, pull requests merged in 2023-07, with the labels that each got.

#1112 Other: print unique detections by rule ID instead of file path
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
Labels: invalid

#1122 fixed result summary table breaks
  src/afterfact.rs
Labels: enhancement

#1123 added category filtering
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
  test_files/rules/level_yaml/critical.yml
  test_files/rules/level_yaml/high.yml
Labels: enhancement

#1121 added `--exclude-tags` option with tags filtering
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1120 added new feature `-P, --proven-rules`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1126 added clobber option and fixed file exist check bug
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/main.rs
Labels: invalid

#1124 added new features filtering on computer names
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/pivot.rs
  src/options/profile.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#1127 added `computer-metrics` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/detections/configs.rs
  src/detections/detection.rs
  src/main.rs
  src/timeline/computer_metrics.rs
  src/timeline/mod.rs
  src/timeline/timelines.rs
Labels: enhancement

#1131 added `include-eid` and `exclude-eid` filtering option in `csv-timeline`, `json-timeline`, `pivot-keywords-list`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1132 feat: Field data mapping (code -> message)
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/field_data_map.rs
  src/detections/message.rs
  src/detections/mod.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/timeline/search.rs
  src/yaml.rs
Labels: enhancement

#1138 supported different time formats in the `search` command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/timeline/search.rs
Labels: enhancement

#1140 Renamed `--live_analysis` option with `--live-analysis`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/main.rs
Labels: enhancement

#1137 changed progress bar width
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement

#1141 print rule count by rule id instead of path
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/yaml.rs
Labels: invalid

#1144 Update progress bar
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#1149 Fixed `--timeline-start` and `--timeline-end` do not work correctly with `json-timeline` command.
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: bug
