Repository Yamato-Security/hayabusa, pull requests merged in 2023-08, with the labels that each got.

#1151 1150 timeline start and timeline end do not work with pivot keywords list
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: bug

#1153 Added `--timeline-start` and `--timeline-end` to `logon-summary` command.
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/main.rs
  src/timeline/timelines.rs
Labels: enhancement

#1154 feat: add `HexToDecimal` field data mapping
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/field_data_map.rs
Labels: enhancement

#1155 fix: Update GitHub Actions for Integration test
  .github/workflows/integration-test.yml
Labels: enhancement

#1147 enabled recover record option in hayabusa-evtx crate #952
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/timeline/computer_metrics.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#1156 update readme verbose section
  Cargo.lock
  README-Japanese.md
  README.md
  screenshots/Startup.png
  src/main.rs
  src/yaml.rs
Labels: enhancement

#1161 feat: exclude `%EvtxFile%` profile duplication check when `-X` enabled
  src/afterfact.rs
Labels: enhancement

#1163 added `--and-logic` to keyword in `search` option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/timeline/search.rs
Labels: enhancement

#1164 added `RecoveredRecord` column to the output profile
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/profile.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: enhancement

#1169 Remove deprecated chrono function use
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/field_data_map.rs
  src/detections/message.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/timeline/computer_metrics.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: invalid
