Repository Yamato-Security/hayabusa, pull requests merged in 2024-11, with the labels that each got.

#1467 fix: sort count rule's result filed value
  .github/workflows/timeline-diff.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/detection.rs
Labels: enhancement

#1465 feat: load `windash` characters dynamically
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/detections/rule/matchers.rs
  src/main.rs
Labels: enhancement

#1476 feat: add RDS log to `logon-summary`
  .github/workflows/timeline-diff.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: enhancement

#1482 fix: not output stdout err msg when timestamp parse error in metrics cmd
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
  src/timeline/metrics.rs
Labels: bug

#1484 feat: add `log-metrics` command feature
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/timeline/log_metrics.rs
  src/timeline/metrics.rs
  src/timeline/mod.rs
  src/timeline/search.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#1488 fix: broken terminal Table/Progress bar completion
  src/main.rs
Labels: bug

#1490 rename timeline_offset to time_offset
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/timeline/computer_metrics.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#1495 fix: invalid first/last timestamp in `log-metrics` command
  src/timeline/log_metrics.rs
  src/timeline/metrics.rs
Labels: bug

#1493 feat: add opening/closing messages
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/options/update.rs
Labels: enhancement

#1497 feat: add `--disable-abbreviations` option
  .github/workflows/integration-test.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#1498 feat: output field information in green and messages in orange
  .github/workflows/integration-test.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  contributors.txt
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/utils.rs
  src/main.rs
  src/timeline/timelines.rs
Labels: enhancement

#1500 feat: add file size next to file name under the progress bar
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#1502 fix: restore stdout color
  src/main.rs
Labels: bug

#1503 feat: `utf16/utf16be/utf16le/wide` modifiers
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/base64_match.rs
  src/detections/rule/fast_match.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
Labels: enhancement

#1507 readme update for 2.19.0
  CHANGELOG-Japanese.md
  README-Japanese.md
  README.md
  screenshots/LogMetrics.png
  screenshots/Mojibake.png
  screenshots/MojibakeFix.png
  screenshots/Startup.png
Labels: documentation

#1518 reduce clone in search.rs
  src/timeline/search.rs
Labels: enhancement

#1521 fix: added sorting by Event RecordID
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
Labels: bug
