Repository Yamato-Security/hayabusa, pull requests merged in 2024-05, with the labels that each got.

#1334 feat: exclude rules/evtx when target `Channel` does not exists in files
  .github/workflows/integration-test.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/filter.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1336 feat: adjusted multiple directory option #1335
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/utils.rs
  src/main.rs
Labels: enhancement

#1341 feat: add support for multiple key grouping in count condition
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/detection.rs
  src/detections/rule/aggregation_parser.rs
  src/detections/rule/count.rs
Labels: enhancement

#1345 chg: disable `Channel` filter when `-J, --JSON-input` option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/main.rs
Labels: bug

#1346 feat(main): adjusted splunk api json format #1083
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/main.rs
Labels: enhancement

#1347 output `-` when count rules's output has no content
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
Labels: enhancement

#1352 feat: add support for `Data[x]` notation and `Provider_Name`(field mapping feature's config)
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/field_data_map.rs
  src/detections/message.rs
  src/detections/utils.rs
Labels: enhancement

#1353 add commits badge
  README-Japanese.md
  README.md
Labels: documentation

#1355 fix commits link
  README-Japanese.md
  README.md
Labels: documentation
