Repository Yamato-Security/hayabusa, pull requests merged in 2024-03, with the labels that each got.

#1286 Adjusted json input from json export from splunk
  CHANGELOG-Japanese.md
  CHANGELOG.md
  contributors.txt
  src/detections/detection.rs
  src/main.rs
  src/timeline/metrics.rs
Labels: enhancement

#1293 Update readme 2024 03 02
  README-Japanese.md
  README.md
  screenshots/ComputerMetrics.png
  screenshots/EID-Metrics.png
  screenshots/LogonSummaryFailedLogons.png
  screenshots/LogonSummarySuccessfulLogons.png
  src/main.rs
Labels: documentation

#1296 removed choosing some options time from elapsed time
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/debug/checkpoint_process_timer.rs
  src/detections/utils.rs
  src/main.rs
  src/timeline/computer_metrics.rs
  src/timeline/timelines.rs
Labels: bug

#1300 reorder `search` result fields
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
  src/timeline/search.rs
  src/timeline/timelines.rs
Labels: enhancement

#1302 added low memory mode option and organize menu
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1305 added goku ascii art
  CHANGELOG-Japanese.md
  CHANGELOG.md
  art/goku.txt
  src/main.rs
Labels: enhancement

#1307 fixed BSides typo
  README-Japanese.md
  README.md
Labels: documentation

#1310 Formatted output numbers
  src/detections/detection.rs
  src/main.rs
  src/options/htmlreport.rs
Labels: enhancement

#1313 update logo
  art/logo.txt
Labels: enhancement

#1315 Fixed computer metrics usage is different
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: invalid

#1316 Fixed `-h, --help` option is being displayed multiple times
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
Labels: invalid
