Repository Yamato-Security/hayabusa, pull requests merged in 2024-02, with the labels that each got.

#1262 removed new line characters in search output
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/timeline/search.rs
Labels: invalid

#1261 fixed `search` command line options associate
  README.md
  src/detections/configs.rs
Labels: invalid

#1268 Remove replace subtoken
  src/detections/rule/condition_parser.rs
Labels: enhancement

#1265 Changed `Details` output in `json-timeline` output to original rule order
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/message.rs
Labels: invalid

#1270 reduce the number of AndContainer's and OrContainer's instance
  src/detections/rule/condition_parser.rs
Labels: enhancement

#1269 Fixed progress bar and wizard colored output when `--no-color` option is used
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/timeline/search.rs
Labels: bug

#1266 added back `-h, --help` option to General Options
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/level_tuning.rs
  src/options/profile.rs
  src/options/update.rs
  src/timeline/computer_metrics.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
  src/yaml.rs
Labels: enhancement

#1272 modified output csv timeline standard output in color
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  config/default_profile.yaml
  config/level_color.txt
  config/profiles.yaml
  src/afterfact.rs
Labels: enhancement

#1274 finalize 2.13.0
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  screenshots/Results.png
  screenshots/ResultsSummary.png
  src/detections/configs.rs
Labels: enhancement

#1276 fixed json output of `search` command is missing `allfieldinfo` field
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/timeline/search.rs
Labels: bug

#1280 added `--include-status` option
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1282 remove unused crates
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: enhancement

#1287 perf: use slice instead of `replacen` in ConditionCompiler.tokenize()
  src/detections/rule/condition_parser.rs
Labels: enhancement

#1288 perf: use slice instead of `replacen` in AggegationConditionCompiler.tokenize()
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/aggregation_parser.rs
Labels: enhancement

#1290 added Bsides Tokyo 2024 badge #1289
  README-Japanese.md
  README.md
  src/detections/configs.rs
Labels: documentation
