Repository Yamato-Security/hayabusa, pull requests merged in 2024-08, with the labels that each got.

#1390 fix(afterfact): modified output format from "-" str to empty Dict in …
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: invalid

#1394 fix: Rule Author does not appear in the terminal
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug

#1395 chg: Sigma v2 compliant `MitreTactics` tag format
  CHANGELOG-Japanese.md
  CHANGELOG.md
  config/mitre_tactics.txt
Labels: enhancement

#1385 feat: embedded config files to binary #1370
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/message.rs
  src/detections/utils.rs
  src/main.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1399 feat: add support for Sigma v2 `|re` sub modifiers
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#1400 added sigma v2 exists modifier support
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#1404 added SecTor Badge
  README-Japanese.md
  README.md
Labels: documentation

#1405 doc: update --sort-events option description
  README-Japanese.md
  README.md
Labels: documentation
