Repository Yamato-Security/hayabusa, pull requests merged in 2024-07, with the labels that each got.

#1378 test: add GitHub Actions for (json/csv)timeline diff check
  .github/workflows/timeline-diff.yml
Labels: enhancement

#1380 added badge
  README-Japanese.md
  README.md
Labels: documentation

#1384 fix: count up `Event with hits` when aggregation/correlation rule
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/detections/rule/count.rs
  src/detections/rule/mod.rs
Labels: bug

#1387 fix: output correlation(and referenced) rule count
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  src/detections/detection.rs
  src/yaml.rs
Labels: bug
