Repository Yamato-Security/hayabusa, pull requests merged in 2024-10, with the labels that each got.

#1419 feat: support encoded rules to avoid AV false positives
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/main.rs
  src/yaml.rs
Labels: enhancement

#1421 add links to readme
  README-Japanese.md
  README.md
Labels: documentation

#1423 feat: load config files from a single file
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/detections/field_data_map.rs
  src/detections/utils.rs
  src/filter.rs
  src/main.rs
Labels: enhancement

#1424 feat: add GitHub Actions for auto build packages
  .github/workflows/release.yml
Labels: enhancement

#1426 fix: remove unnecessary line break in `search` cmd
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/search.rs
Labels: bug

#1428 test: add integration-test/csv(json)-timeline diff-test for encoded_rules/single config
  .github/workflows/integration-test.yml
  .github/workflows/timeline-diff.yml
Labels: enhancement

#1430 fix: copy all .git commit history by specifying fetch-depth
  .github/workflows/release.yml
Labels: bug

#1436 fix: specify compile target explicitly in Release Automation
  .github/workflows/release.yml
Labels: bug

#1437 chg: Create `fieldref|endswith` alias for `endswithfield`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#1441 feat: add support for `fieldref|startswith` and `fieldref|contains`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
Labels: enhancement

#1443 fix: make `group-by` optional for correlation
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/correlation_parser.rs
Labels: bug

#1449 fix: give a parsing error when correlation reference rule not found
  .github/workflows/timeline-diff.yml
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/correlation_parser.rs
Labels: bug

#1451 change license to AGPL
  CHANGELOG-Japanese.md
  CHANGELOG.md
  LICENSE.txt
  README-Japanese.md
  README.md
Labels: enhancement

#1452 fix: output agg result string when `all-field-info` profile
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/message.rs
Labels: bug

#1454 explain channel filtering
  README-Japanese.md
  README.md
Labels: documentation

#1456 Channel filtering typo
  README-Japanese.md
  README.md
Labels: documentation

#1460 add 2.18.0 documentation
  README-Japanese.md
  README.md
Labels: documentation

#1461 fix: Changed Release automation Action's Artifact name
  .github/workflows/release.yml
Labels: bug

#1462 fix: output completion message when scan is finished
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/main.rs
Labels: bug

#1463 feat: add support v2 modifier(ge/gte/lt/lte)
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/rule/matchers.rs
  src/detections/rule/selectionnodes.rs
Labels: enhancement
