Repository Yamato-Security/hayabusa, pull requests merged in 2025-09, with the labels that each got.

#1683 fix: remove unused dependency
  Cargo.lock
  Cargo.toml
Labels: bug

#1695 fix: JSON timeline flag in geo IP lookup
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/detection.rs
  src/options/geoip_search.rs
Labels: bug

#1700 feat: add detection timestamp tracking in AfterfactInfo
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/main.rs
Labels: enhancement

#1701 Update sof elk docs
  README-Japanese.md
  README.md
  doc/ElasticStackImport/01-SOF-ELK-Bootup.png
  doc/ElasticStackImport/03-ChangeDates.png
  doc/ElasticStackImport/03-Integrations.png
  doc/ElasticStackImport/04-IntegrationsImportCSV.png
  doc/ElasticStackImport/04-TotalRecords.png
  doc/ElasticStackImport/05-OpenDiscover.png
  doc/ElasticStackImport/05-OverrideSettings.png
  doc/ElasticStackImport/06-Discover.png
  doc/ElasticStackImport/06-OverrideSettingsConfig.png
  doc/ElasticStackImport/07-AddingColumns.png
  doc/ElasticStackImport/07-CSV-Import.png
  doc/ElasticStackImport/08-DiscoverWithColumns.png
  doc/ElasticStackImport/08-ImportDataSettings.png
  doc/ElasticStackImport/09-ImportFinish.png
  doc/ElasticStackImport/09-ToggleDetails.png
  doc/ElasticStackImport/10-Discover.png
  doc/ElasticStackImport/10-ViewSurroundingDocuments.png
  doc/ElasticStackImport/11-Dashboard.png
  doc/ElasticStackImport/11-SurroundingDocuments.png
  doc/ElasticStackImport/12-LevelMetrics.png
  doc/ElasticStackImport/13-RecommendedColumns.png
  doc/ElasticStackImport/14-DicoverWithColumns.png
  doc/ElasticStackImport/15-HayabusaDashboard-StackManagement.png
  doc/ElasticStackImport/16-HayabusaDashboard-Import.png
  doc/ElasticStackImport/17-HayabusaDashboard-1.png
  doc/ElasticStackImport/18-HayabusaDashboard-2.png
  doc/ElasticStackImport/6650-hayabusa-jsonl.conf
  doc/ElasticStackImport/ElasticStackImport-English.md
  doc/ElasticStackImport/ElasticStackImport-Japanese.md
  doc/ElasticStackImport/HayabusaDashboard.ndjson
Labels: documentation
