Repository Yamato-Security/hayabusa, pull requests merged in 2025-01, with the labels that each got.

#1542 fix: modify csv-timeline help msg
  src/detections/configs.rs
Labels: bug

#1545 feat: add timeline-start/timeline-end option to search command
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/detections/configs.rs
  src/yaml_expand.rs
Labels: enhancement

#1547 feat: add channel filter to logon-summary
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#1550 1549 add power shell classic eid400 to extract-base64
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/timeline/extract_base64.rs
Labels: enhancement

#1552 feat: add `-X, --remove-duplicate-detections` option to `eid-metrics` and `logon-summary`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/configs.rs
  src/main.rs
  src/timeline/metrics.rs
  src/timeline/timelines.rs
Labels: enhancement

#1554 fix: not create unnecessary output file in `logon-summary` and `pivot-keywords-list`
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
Labels: bug

#1559 fix: compile error ureq v3
  Cargo.lock
  src/main.rs
  src/options/update.rs
Labels: bug

#1561 update timesketch docs
  doc/TimesketchImport/01-TimesketchLogin.png
  doc/TimesketchImport/02-NewInvestigation.png
  doc/TimesketchImport/03-TimesketchTimeline.png
  doc/TimesketchImport/04-TimelineWithColumns.png
  doc/TimesketchImport/05-FieldInformation.png
  doc/TimesketchImport/06-MarkingEvents.png
  doc/TimesketchImport/AlertDetails.png
  doc/TimesketchImport/CommentChat.png
  doc/TimesketchImport/CommentIcon.png
  doc/TimesketchImport/ContextSearch.png
  doc/TimesketchImport/Details.png
  doc/TimesketchImport/EventDataAnalytics.png
  doc/TimesketchImport/EventHistogram.png
  doc/TimesketchImport/FilterInOut.png
  doc/TimesketchImport/ModifyColumnsIcon.png
  doc/TimesketchImport/MoreRoom.png
  doc/TimesketchImport/SearchHistory.png
  doc/TimesketchImport/SelectColumns.png
  doc/TimesketchImport/StarsAndTags.png
  doc/TimesketchImport/TimesketchImport-English.md
  doc/TimesketchImport/TimesketchImport-Japanese.md
  doc/TimesketchImport/TimesketchResults.png
  doc/TimesketchImport/TooMuchDetails.png
  doc/TimesketchImport/VerticalElipsisContext.png
Labels: documentation
