Repository Yamato-Security/hayabusa, pull requests merged in 2025-02, with the labels that each got.

#1569 feat: Level adjusting depending on `config/critical_systems.txt` - "Emergency Alerts"
  .gitignore
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  config/critical_systems.txt
  config/html_report/hayabusa_report.css
  config/level_color.txt
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/message.rs
  src/level.rs
  src/lib.rs
Labels: enhancement

#1574 fix: output rule author in html report
  CHANGELOG-Japanese.md
  CHANGELOG.md
  config/html_report/hayabusa_report.css
  src/afterfact.rs
Labels: bug

#1575 fix: mitre tactics tag in json-timeline
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/detection.rs
Labels: bug

#1576 fix: output `RuleFile` field in json-timeline
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/detections/detection.rs
Labels: bug

#1581 update level-tuning doc
  README-Japanese.md
  README.md
Labels: documentation

#1585 feat: add system 7045 to extract-base64
  CHANGELOG-Japanese.md
  CHANGELOG.md
  README-Japanese.md
  README.md
  src/timeline/extract_base64.rs
Labels: enhancement

#1586 fix: level-tuning command is not working
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/main.rs
Labels: bug

#1588 refactor: use Default trait to reduce unnecessary initialization codes in StoredStatic
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/matchers.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/main.rs
  src/options/htmlreport.rs
  src/options/profile.rs
  src/yaml.rs
Labels: enhancement

#1590 fix: remove extra comma
  src/afterfact.rs
Labels: bug

#1591 feat: add tab-seperator option in csv-timeline/search/log-metrics
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/rule/mod.rs
  src/main.rs
  src/options/htmlreport.rs
  src/timeline/search.rs
  src/timeline/timelines.rs
Labels: enhancement

#1593 3.1.0 readme update
  README-Japanese.md
  README.md
  doc/TimelineExplorerAnalysis/15-FieldInformation.png
  doc/TimelineExplorerAnalysis/16-CellContents.png
  doc/TimelineExplorerAnalysis/17-MultilineFormatting.png
  doc/TimelineExplorerAnalysis/18-MultilineSingleField.png
  doc/TimelineExplorerAnalysis/19-TabSeparation.png
  doc/TimelineExplorerAnalysis/20-TabSeparationNotFormatted.png
  doc/TimelineExplorerAnalysis/21-TabSeparationFormatted.png
  doc/TimelineExplorerAnalysis/TimelineExplorerAnalysis-English.md
  doc/TimelineExplorerAnalysis/TimelineExplorerAnalysis-Japanese.md
  screenshots/ResultsSummary.png
Labels: documentation

#1595 update to Rust 2024
  CHANGELOG-Japanese.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/afterfact.rs
  src/detections/configs.rs
  src/detections/detection.rs
  src/detections/field_data_map.rs
  src/detections/message.rs
  src/detections/rule/base64_match.rs
  src/detections/rule/condition_parser.rs
  src/detections/rule/correlation_parser.rs
  src/detections/rule/count.rs
  src/detections/rule/fast_match.rs
  src/detections/rule/matchers.rs
  src/detections/rule/mod.rs
  src/detections/rule/selectionnodes.rs
  src/detections/utils.rs
  src/filter.rs
  src/main.rs
  src/options/expand_list.rs
  src/options/geoip_search.rs
  src/options/htmlreport.rs
  src/options/pivot.rs
  src/options/profile.rs
  src/options/update.rs
  src/timeline/computer_metrics.rs
  src/timeline/config_critical_systems.rs
  src/timeline/extract_base64.rs
  src/timeline/search.rs
  src/timeline/timelines.rs
  src/yaml.rs
  src/yaml_expand.rs
Labels: enhancement

#1600 fix: expand rule count logic
  CHANGELOG-Japanese.md
  CHANGELOG.md
  src/yaml.rs
  src/yaml_expand.rs
Labels: bug
